#ifndef SF_CONSOLE_CFG_H_
#define SF_CONSOLE_CFG_H_

#define SF_CONSOLE_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#define SF_CONSOLE_MAX_INPUT_LENGTH (128U)
#define SF_CONSOLE_MAX_WRITE_LENGTH (128U)
#define SF_CONSOLE_PRV_TIMEOUT (0xFFFFFFFFUL)

#endif /* SF_CONSOLE_CFG_H_ */
